version: "2"
services:
  ledger-server:
    container_name: ledger
    build:
      context: .
      dockerfile: ./ledger-server/Dockerfile.dev
    volumes:
      - .:/go/src/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000