[run]
init_cmds = [
    ["go", "install"],
    ["go", "build", "-o", "/tmp/app"],
    ["/tmp/app"]
]     # Commands run in start
watch_all = true                # Watch all sub-directories
watch_dirs = [
    "../proto"
]                               # Directories to watch
watch_exts = [".go"]    # Extensions to watch
ignore = [".git", "node_modules"] # Directories to exclude from watching
ignore_files = []             # Regexps for ignoring specific notifies
build_delay = 1500              # Minimal interval to Trigger build event
cmds = [
    ["go", "install"],
    ["go", "build", "-o", "/tmp/app"],
    ["/tmp/app"]
]                               # Commands to run